---
resources:
  - name: source-code
    type: git
    source:
      uri: git@github.com:((GITHUB_REPO_ACCOUNT))/((PRODUCT))-((COMPONENT))
      branch: master
      password: ((GITHUB_API_TOKEN))
      private_key: ((GITHUB_DEPLOY_KEY.private_key))
jobs:
  - name: build
    public: true
    plan:
      - get: source-code
        trigger: true
      - task: test
        file: source-code/devops/concourse/tasks/build.yml

